### ISSUE TITLE
Hide the arrow when data is empty.

### ISSUE THREAD

**Issue by rafacianci** [viniciusdacal/angular-select#5]

**Comment by rafacianci** [comment]
When its closed it showing the arrow.
![captura de tela 2016-02-18 as 09 13 38](https://cloud.githubusercontent.com/assets/4905837/13141730/fd24403e-d61f-11e5-926e-2299c13bedcb.png)

But when I enter there its nothing to select.
![captura de tela 2016-02-18 as 09 13 51](https://cloud.githubusercontent.com/assets/4905837/13141731/fd430226-d61f-11e5-9d1b-e21fa7c5c04e.png)

**Comment by viniciusdacal** [comment]
closed by #7
